### ISSUE TITLE
ISBD Antenna Cable

### ISSUE THREAD

**Issue by AaronKehl** [AaronKehl/Single_Beam_Range_Finder_Campbell#1]
In need of a TNC-M plug to SMA-M plug coaxial cable (RG-400U) to connect the ISBD Modem to the ISBD Antenna

**Comment by jm-hodge** [comment]
I have a:

-SMA 132195 https://www.mouser.com/ProductDetail/Amphenol-RF/132195?qs=Kdyc7Q8pFhrL27pFl1hc7g%3D%3D

-TNC 122372 https://www.mouser.com/ProductDetail/Amphenol-RF/122372?qs=8wOOb4nECAsnC3SM1sAtlw%3D%3D

Cable will be 8" long. I'll make 2 of them.

**Comment by AaronKehl** [comment]
Excellent, thank you Jordan

**Comment by jm-hodge** [comment]
3 Cables for you bro

![20200526_132155](https://user-images.githubusercontent.com/65786515/82930847-05b46880-9f54-11ea-88b2-066cd7376a5f.jpg)

**Comment by AaronKehl** [comment]
Those are perfect!

**Comment by jm-hodge** [comment]
[132195-713180.pdf](https://github.com/AaronKehl/Single_Beam_Range_Finder_Campbell/files/4683975/132195-713180.pdf)

**Comment by jm-hodge** [comment]
[122372-710788.pdf](https://github.com/AaronKehl/Single_Beam_Range_Finder_Campbell/files/4683980/122372-710788.pdf)
