### ISSUE TITLE
CR100X

### ISSUE THREAD

**Issue by jm-hodge** [AaronKehl/Single_Beam_Range_Finder_Campbell#10]
Need 1 CR100X for Unit 3

**Comment by jm-hodge** [comment]
Aaron please check your inventory for an extra CR1000X

**Comment by AaronKehl** [comment]
Yes, I have the necessary CR1000X. Next time we meet up, I will have it with me! Good to see you today

**Comment by AaronKehl** [comment]
Will close out issue once CR1000X is transferred from Aaron to Jordan.

**Comment by AaronKehl** [comment]
Transferred to Jordan.
